---
- name: Disable dash as /bin/sh, use bash instead
  debconf:
    name: dash
    question: dash/sh
    value: 'false'
    vtype: boolean
  register: dash_debconf
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_dash }}"

- name: reconfigure dash
  command: dpkg-reconfigure -f noninteractive dash
  when: dash_debconf.changed
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_dash }}"

