---
- name: install archive utilities
  apt:
    state: latest
    pkg:
      - unzip
      - bzip2
      - arj
      - nomarch
      - lzop
      - cabextract
      - p7zip
      - p7zip-full
      - lrzip
      - zip
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install dovecot
  apt:
    state: latest
    pkg:
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-mysql
      - dovecot-sieve
      - dovecot-lmtpd
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install getmail4
  apt:
    state: latest
    pkg: getmail4
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install postgrey
  apt:
    state: latest
    pkg: postgrey
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install amavis
  apt:
    state: latest
    pkg:
      - amavisd-new
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install clamav
  apt:
    state: latest
    pkg:
      - clamav
      - clamav-daemon
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

- name: install spamassassin
  apt:
    pkg:
      - spamassassin
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"

#- name: copy our dovecot.conf
#  template:
#    src: dovecot/dovecot.conf.j2
#    dest: "/etc/dovecot/dovecot.conf"
#  notify: restart dovecot

# 
# SA is used through amavis
# 
- name: stop and disable spamassassin
  systemd:
    name: spamassassin
    state: stopped
    enabled: false
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_mail }}"
