---
- name: configure shell
  include_tasks: 10_core/dash.yml

- name: install certbot
  include_tasks: 10_core/certbot.yml

- name: install postfix
  include_tasks: 10_core/postfix.yml

- name: install&configure apache2
  include_tasks: 10_core/apache2.yml

- name: install mail daemons
  include_tasks: 10_core/mail.yml

- name: install&configure system quota
  include_tasks: 10_core/quota.yml
  when: enable_quota

- name: install&configure pure-ftpd
  include_tasks: 10_core/pureftpd.yml

- name: install&configure web statistics tools
  include_tasks: 10_core/web-statistics.yml


- name: install ispconfig
  include_tasks: '{{ item }}'
  loop:
    - 20_ispconfig/00_secrets.yml
    - 20_ispconfig/10_install_or_update.yml
    - 20_ispconfig/20_configure.yml
    - 20_ispconfig/21_create_api_user.yml
    - 20_ispconfig/30_apps_site.yml
    - 20_ispconfig/40_ssl.yml

- name: configure mailserver role
  include_tasks: 30_server_roles/mailserver.yml

- name: configure ftp role
  include_tasks: 30_server_roles/pureftpd.yml

- name: install&configure phpmyadmin
  include_tasks: 40_apps/phpmyadmin.yml

- name: install&configure roundcube
  include_tasks: 40_apps/roundcube.yml

- name: create limited account after ispconfig first install
  include_tasks: 50_user/firstinstall_create_user.yml

- name: install security tools
  include_tasks: 60_enhancements/security.yml

