---
#
# Load or generate secrets
#
- name: Ensure we have ISPConfig secrets
  password_file:
    path: "{{ ispconfig_private_dir }}/secrets/{{ item.name }}"
    set_fact: "{{ item.name }}"
    length: "{{ item.length }}"
    state: present
  with_items:
    - name: mysql_ispconfig_password
      length: 20
