---
#
# Create API user
#
- name: Generate API users passwords
  password_file:
    path: "{{ ispconfig_private_dir }}/secrets/{{ item.name }}"
    set_fact: "{{ item.name }}"
    length: "{{ item.length }}"
    state: present
  with_items:
    - name: ispconfig_api_admin_password
      length: 24
    - name: ispconfig_api_roundcube_password
      length: 24
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_core }}"
    - "{{ tag_lukasic_ispconfig_configure }}"

- name: Deploy post-install ISPConfig scripts
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "ispconfig/create-api-users.sql.j2"
      dest: "{{ ispconfig_installer_dir }}/ispconfig-create-api-users.sql"
  when: ispconfig_first_install
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_core }}"
    - "{{ tag_lukasic_ispconfig_configure }}"

- name: Create ISPConfig API users
  shell: cat {{ ispconfig_installer_dir }}/ispconfig-create-api-users.sql | mysql _dbispconfig
  when: ispconfig_first_install
  tags:
    - "{{ tag_lukasic_ispconfig }}"
    - "{{ tag_lukasic_ispconfig_core }}"
    - "{{ tag_lukasic_ispconfig_configure }}"
