---
#
# SSL certificate
#

- name: Deploy own / letsecnrypt SSL certificate to ISPConfig admin
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "{{ server_cert_full }}"
      dest: /usr/local/ispconfig/interface/ssl/ispserver.crt
    - src: "{{ server_cert_key }}"
      dest: /usr/local/ispconfig/interface/ssl/ispserver.key
  notify: restart apache2

- name: Remove ISPConfig certificate relics
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/ispconfig/interface/ssl/ispserver.key.secure
    - /usr/local/ispconfig/interface/ssl/ispserver.csr
  notify: restart apache2

- name: Restart apache
  service:
    name: apache2
    state: restarted
