---
#
# postfix
#
- name: Update Postfix configuration.
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }}\\s*="
  loop: "{{ postfix_postconf }}"
  notify: restart postfix

- name: deploy /etc/mailname
  template:
    src: "postfix/mailname.j2"
    dest: "/etc/mailname"
  notify: restart postfix

- name: master.cf
  template:
    src: "postfix/master.cf.j2"
    dest: "/etc/postfix/master.cf" 
  notify: restart postfix

- name: set virtual_alias_maps
  template: 
    src: "postfix/virtual_alias_maps.j2"
    dest: "/etc/postfix/virtual_alias_maps"
  register: virtual_alias_maps

- name: postmap virtual_alias
  command: postmap /etc/postfix/virtual_alias_maps
  when: virtual_alias_maps.changed

- name: delete aliases from /etc/aliases
  command: echo > /etc/aliases
  when: virtual_alias_maps.changed

- name: delete postfix self-signed keys
  file:
    path: /etc/postfix/{{ item }}
    state: absent
  with_items:
    - smtpd.key
    - smtpd.cert

#
# dovecot
#
- name: generate Diffie-Hellman parameters for dovecot
  openssl_dhparam:
    path: "{{ dovecot_dh_params }}"
    size: 2048

- name: ensure we have cured dovecot.conf
  template:
    src: dovecot/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
  notify: restart dovecot
